# Generated by Django 5.0.7 on 2024-07-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_broowrecord_borrowrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_date',
            field=models.CharField(max_length=100),
        ),
    ]
